version: '3'

services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3002:3002'
    environment:
      - NODE_ENV=development
