version: '3'
services:

  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/vsign
    ports:
      - "3000:3000"
    depends_on:
      - db


  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/app'
      # One-way volume to use node_modules from inside image
      - '/app/node_modules'
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
