site_name: Vsign
nav:
    - Home: README.md
    - Projeto: 
        - 'Documento de Arquitetura': 'project/architectureDocument.md'
        - 'Documento de Visão': 'project/vision-document.md'
    - Gerenciamento de Projeto: 
        - 'Plano de Gerenciamento de Configuração de Software': 'managementProject/gcs.md'
    - Documentar Sprint:
        - 'Sprint 0': 'sprints/sprint0.md'
theme: readthedocs
