site_name: Desafio
nav:
    - Home: README.md
    - Documento de Arquitetura: 'architectureDocument/doc.md'
    - Gerenciamento de Projeto: 
        - 'Plano de Gerenciamento de Configuração de Software': 'managementProject/gcs.md'
theme: readthedocs
